spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Workspaces/intellij/workspace_springlemon/np-microservices-sample-01-config
  security:
    user:
      password: topsecret
         